<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_first</name>
   <tag></tag>
   <elementGuidId>31d792d0-ce5e-43aa-9d0b-f32f1d21c3ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#first</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'first' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First Name *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea2edf9a-dc6c-4bac-adf5-c4737b06ec64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>913e0fa6-04fd-459f-b1fc-885b9704ea14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>first</value>
      <webElementGuid>b4fc3bda-8492-407f-bb27-9e01d39e63f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8af976d-e335-4b2c-a5bc-25886f07246f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>f26d4284-1771-4a83-b9d9-c92b758700c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;first&quot;)</value>
      <webElementGuid>91b85e9f-9462-4477-b78e-df71bff549b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'first' and @type = 'text']</value>
      <webElementGuid>6debd52a-ff28-4616-92d0-05ce4d2ed782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='first']</value>
      <webElementGuid>cda267a3-47b6-43ff-89b4-695732f8f390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div/div/div/div/div/div/input</value>
      <webElementGuid>3e98453a-cf05-4bb6-bf9a-c66b14509a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>82e57114-92be-43ab-8cd1-313c3c40780f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
