<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Are you currently incarcerated</name>
   <tag></tag>
   <elementGuidId>e709d1f2-512a-4823-b2c4-054a61fd7a17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#incarcerated-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id = 'incarcerated-label' and (text() = 'Are you currently incarcerated? *' or . = 'Are you currently incarcerated? *')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Are you currently incarcerated? *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ba043533-c62e-4605-a004-99b0e7b9c101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormLabel-root MuiFormLabel-colorPrimary Mui-required css-88235q</value>
      <webElementGuid>0a7aa42e-f8ac-4148-ad51-7eef3917635b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>incarcerated-label</value>
      <webElementGuid>89677d6c-f90f-4896-8266-72107c65dacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Are you currently incarcerated? *</value>
      <webElementGuid>1d31b0eb-fdc8-438f-bb41-f07e4e4e925d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;incarcerated-label&quot;)</value>
      <webElementGuid>1023f0c0-5d12-4808-a381-cfcde3c93818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'incarcerated-label' and (text() = 'Are you currently incarcerated? *' or . = 'Are you currently incarcerated? *')]</value>
      <webElementGuid>f7e26340-734f-42d8-898b-e741531f83d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='incarcerated-label']</value>
      <webElementGuid>74ef54f5-c80e-4dda-bb24-3d6226869ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[2]/div/div[2]/div/label</value>
      <webElementGuid>e94ca63e-7a40-48c1-a7d7-4440fd5dbd31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::label[1]</value>
      <webElementGuid>b09199fa-ade7-46a5-932b-f36e1500bec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::label[2]</value>
      <webElementGuid>03c344fe-8d2d-4060-a817-edc177e8c30d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[2]/preceding::label[1]</value>
      <webElementGuid>c3a49f4d-24d7-409a-83aa-5bb2701ec531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::label[2]</value>
      <webElementGuid>67c756a3-7a00-448e-90c4-e16eb2820b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Are you currently incarcerated?']/parent::*</value>
      <webElementGuid>a9ba8ae3-745e-4dd6-bf02-a61642ab8d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/label</value>
      <webElementGuid>3e51f178-642c-4f28-b1a3-fe404c609380</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
