<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Password_a-6r4655n35qm</name>
   <tag></tag>
   <elementGuidId>5617756f-2e30-46fa-af49-a0e55e10a63b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-6r4655n35qm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-6r4655n35qm&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-6r4655n35qm&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2010b833-a626-49d5-b742-42c529691b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>4b23bea3-a2fe-4894-831e-b420f5c26100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>38e1bba2-4050-407b-9555-e7f4ac4a89a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>599744a6-619a-4400-a98e-cafea415d551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>889f627c-681d-4b83-a367-b59a7366981a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-6r4655n35qm</value>
      <webElementGuid>27e4a29c-758e-4687-96cb-be1b315f9018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d78f8698-291d-4bd1-9cc8-60e0552726d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f8a00843-5e75-4d92-9421-74541c67ab70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>d190fc82-9194-42e0-81f1-6809704d3f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;co=aHR0cHM6Ly9jb21tdW5pdHktZGV2LnJldm9uZS5pbzo0NDM.&amp;hl=en&amp;type=image&amp;v=44LqIOwVrGhp2lJ3fODa493O&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=etimy3u8t5bl</value>
      <webElementGuid>7a293007-346d-425a-a9b0-e7fb312b9110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiGrid-root MuiGrid-container css-17r26s3&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item css-f068ot&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 css-3qgq5l&quot;]/form[1]/div[@class=&quot;MuiGrid-root MuiGrid-container css-12q1jqj&quot;]/div[1]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>f0cc56da-64f7-4ec6-bdeb-2b278e941ad1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-6r4655n35qm']</value>
      <webElementGuid>f56b2947-6413-490b-a960-cb7670c98491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/form/div[2]/div/div/div/div/iframe</value>
      <webElementGuid>f24b1e1a-4685-4105-80d0-8a762a6dc2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>432f38d4-2dde-46fb-8054-1ae91e6b06cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-6r4655n35qm' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;co=aHR0cHM6Ly9jb21tdW5pdHktZGV2LnJldm9uZS5pbzo0NDM.&amp;hl=en&amp;type=image&amp;v=44LqIOwVrGhp2lJ3fODa493O&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=etimy3u8t5bl']</value>
      <webElementGuid>c669221c-27e3-417f-b0f3-5f325c60e72b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
