<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_html1body1div2div4iframe1_c-w2lq6orjlzi7</name>
   <tag></tag>
   <elementGuidId>88ed04b1-d25d-408a-9bf0-f37237793b01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-w2lq6orjlzi7&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-w2lq6orjlzi7' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=KmpMK968ITgSdSG_2lbUmd1o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;bft=0dAFcWeA6WK_SnyGVwPB62sMFsv6vGhfWywi8mk2iIB2uaO9dXtuylfaMQ2ZWmjMoWEEi1hRbsPzcmOyuI7x2EQl6wekRCwarn9g']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;c-w2lq6orjlzi7&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>91501b8a-de71-4969-b606-24a1651e6838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>a6d4f5c3-ce0c-4365-b647-fbf443cbff79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-w2lq6orjlzi7</value>
      <webElementGuid>b97a3228-22e5-420f-bab6-d10f5a24b4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8411bf38-484c-43ae-ae77-67dbf385e864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>fabae082-8983-4cbd-b051-e735081ae7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>df4bd4b9-0c06-40cb-8c1a-6a478e04dca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=KmpMK968ITgSdSG_2lbUmd1o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;bft=0dAFcWeA6WK_SnyGVwPB62sMFsv6vGhfWywi8mk2iIB2uaO9dXtuylfaMQ2ZWmjMoWEEi1hRbsPzcmOyuI7x2EQl6wekRCwarn9g</value>
      <webElementGuid>aa42ab33-a13d-4325-af6d-cec65ee74a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[4]/iframe[1]</value>
      <webElementGuid>f574fd71-9fee-458f-9f38-bce230247a02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-w2lq6orjlzi7' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=KmpMK968ITgSdSG_2lbUmd1o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;bft=0dAFcWeA6WK_SnyGVwPB62sMFsv6vGhfWywi8mk2iIB2uaO9dXtuylfaMQ2ZWmjMoWEEi1hRbsPzcmOyuI7x2EQl6wekRCwarn9g']</value>
      <webElementGuid>13df08cb-db54-4011-aadd-4516af5d4788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-w2lq6orjlzi7']</value>
      <webElementGuid>c342d63a-8eaa-4a16-b81a-feb99bd11460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>3a6bc0ae-64f0-4da8-a8ae-4f465609a31c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
