<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1</name>
   <tag></tag>
   <elementGuidId>eb9a424a-c6e9-45f0-a9e8-c687d58e9f12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-44</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lMw7TKUoYokZewMlIFOOpHH9l_R-UEpMTvKgENRw_ilc7Fn3qeIqT_PyfgIKVf2H1NyyyDUKdVVJWQY2JEiMQwhfg8Wf_7end1w1thcBRV01x0eblI8_pNEe6h8GGO9Aa3UQZJCrApTlQQkidseru-VFfrOTzVzKXGWl0twZX5zRXDMmW-Mx6_iMgYnr1x30DnS_NqcJr9G6Tlo-m8tPJR229ZXKB3rd79-_ZGTtrJbwie-g&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;id=2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\30 &quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>715b4ca6-87c8-4aa1-acdb-e7caf6775246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>af5f84a8-b833-4677-9eba-72fa129541d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lMw7TKUoYokZewMlIFOOpHH9l_R-UEpMTvKgENRw_ilc7Fn3qeIqT_PyfgIKVf2H1NyyyDUKdVVJWQY2JEiMQwhfg8Wf_7end1w1thcBRV01x0eblI8_pNEe6h8GGO9Aa3UQZJCrApTlQQkidseru-VFfrOTzVzKXGWl0twZX5zRXDMmW-Mx6_iMgYnr1x30DnS_NqcJr9G6Tlo-m8tPJR229ZXKB3rd79-_ZGTtrJbwie-g&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;id=2</value>
      <webElementGuid>649f4d30-89d4-4a18-b6e4-e3b2044bc59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0&quot;)/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>84bf03f7-3b24-461d-be10-bcda743f6e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/accvisit/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-w2lq6orjlzi7</value>
      <webElementGuid>fb547617-3b47-4a5c-8ec5-1bcdb7a1f990</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lMw7TKUoYokZewMlIFOOpHH9l_R-UEpMTvKgENRw_ilc7Fn3qeIqT_PyfgIKVf2H1NyyyDUKdVVJWQY2JEiMQwhfg8Wf_7end1w1thcBRV01x0eblI8_pNEe6h8GGO9Aa3UQZJCrApTlQQkidseru-VFfrOTzVzKXGWl0twZX5zRXDMmW-Mx6_iMgYnr1x30DnS_NqcJr9G6Tlo-m8tPJR229ZXKB3rd79-_ZGTtrJbwie-g&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;id=2']</value>
      <webElementGuid>f41418c1-0ec4-4e6a-b4e7-30098c1fb4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='0']/div/div/img</value>
      <webElementGuid>d60a9318-e867-464b-a46c-b21cf8968e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4lMw7TKUoYokZewMlIFOOpHH9l_R-UEpMTvKgENRw_ilc7Fn3qeIqT_PyfgIKVf2H1NyyyDUKdVVJWQY2JEiMQwhfg8Wf_7end1w1thcBRV01x0eblI8_pNEe6h8GGO9Aa3UQZJCrApTlQQkidseru-VFfrOTzVzKXGWl0twZX5zRXDMmW-Mx6_iMgYnr1x30DnS_NqcJr9G6Tlo-m8tPJR229ZXKB3rd79-_ZGTtrJbwie-g&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;id=2')]</value>
      <webElementGuid>ddfd7635-bf7e-42d9-b214-5beb6dc67849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>79514f3a-f36c-4fcc-8d05-32d5f5b46561</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
