<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_IMaskInput-Thu Oct 16 2025 1250_9e3474</name>
   <tag></tag>
   <elementGuidId>41e2d251-9567-4004-95ae-e6e0ace76848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#authorization_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'authorization_phone' and @type = 'text' and @name = 'IMaskInput-Thu Oct 16 2025 12:50:10 GMT+0530 (India Standard Time)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#authorization_phone</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ce9f7ed-5319-439a-aae3-017a1ff7e89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1fae8f4b-e4a4-4697-b443-c1601d90874e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>authorization_phone</value>
      <webElementGuid>a098fbde-3484-47d6-a74a-c749884bab5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1850b282-926b-434a-8c73-c7acc3ff74ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>d28394f0-b554-414a-a6cc-193753c28b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IMaskInput-Thu Oct 16 2025 12:50:10 GMT+0530 (India Standard Time)</value>
      <webElementGuid>8bc5d9bb-91b4-4be4-9102-2a8656eaabb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>19ed5a84-830e-47bd-a452-4a813a340816</value>
      <webElementGuid>7c7b199c-3d33-4ab0-bf63-8d21c6897df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authorization_phone&quot;)</value>
      <webElementGuid>f5bc84ae-1326-45f6-ba4f-4081e97b5f3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'authorization_phone' and @type = 'text' and @name = 'IMaskInput-Thu Oct 16 2025 12:50:10 GMT+0530 (India Standard Time)']</value>
      <webElementGuid>f42191aa-885a-474f-8bec-01667d15c139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='authorization_phone']</value>
      <webElementGuid>262f0f69-3056-4971-972b-6bf8e4cbbfbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[4]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>ce16b296-0132-486a-a0fb-89cf091706ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>1ed32fdc-23ab-4605-a15a-65b60f1393b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
