<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_IMaskInput-Thu Oct 16 2025 1250_0cf929</name>
   <tag></tag>
   <elementGuidId>85c1f3a6-b190-43ea-b8a4-05d17fa1ae2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#authorization_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'authorization_phone' and @type = 'text' and @name = 'IMaskInput-Thu Oct 16 2025 12:50:09 GMT+0530 (India Standard Time)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#authorization_phone</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5468683a-8ba6-4b09-a80a-da497db0fe2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f59361d6-2c8f-4d20-a69b-4d717f3639a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>authorization_phone</value>
      <webElementGuid>34336016-ff71-4cc2-a7ac-9640ca2f467c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a2af952-4838-4518-a54f-164500e12132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>c8f74fbb-8ff2-4d6d-bd08-b23915befebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IMaskInput-Thu Oct 16 2025 12:50:09 GMT+0530 (India Standard Time)</value>
      <webElementGuid>d5cd9ec5-d813-4b4c-b4a9-82de8cdb403a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>19ed5a84-830e-47bd-a452-4a813a340816</value>
      <webElementGuid>e0739f3d-0424-4665-b0a2-ee5fdee9d9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authorization_phone&quot;)</value>
      <webElementGuid>d053af44-35c2-4b23-b62c-c36b39eda8b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'authorization_phone' and @type = 'text' and @name = 'IMaskInput-Thu Oct 16 2025 12:50:09 GMT+0530 (India Standard Time)']</value>
      <webElementGuid>9162d492-06e8-4417-bdcf-d659bb9a9f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='authorization_phone']</value>
      <webElementGuid>d5e846d5-34c8-4c43-90d8-f4aa47c0714b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[4]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>994a264e-a541-43ff-8e21-21188026eea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>a78d0463-68e6-439f-98e6-2676d0ef8126</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
