<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Who was responsible for the accident__afa22a</name>
   <tag></tag>
   <elementGuidId>2e33f580-fd01-4e8d-ae6c-6c5450dadd63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#who_caused_auto_accident</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'who_caused_auto_accident' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Who was responsible for the accident? *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be2b24a1-a739-478b-b8e6-3d24e46a1cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf77d0eb-5e34-46cf-b69a-19c9ec01d9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>who_caused_auto_accident</value>
      <webElementGuid>ccb36455-0894-4ac7-96a9-63ee0824b1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83c21f8a-7b88-48d9-bd98-b95d4e35425a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall MuiInputBase-inputAdornedEnd css-b52kj1</value>
      <webElementGuid>410ae10d-bc1a-4883-9946-8201d7d4d869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>d119aa04-b734-454f-b9ef-ceed9eccc215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>f6c834ac-5792-496d-b739-336ca3efbd14</value>
      <webElementGuid>6882e179-4a26-4f5c-a7b6-17aee374c1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;who_caused_auto_accident&quot;)</value>
      <webElementGuid>530012b1-8be2-442f-9fb3-8de938a27342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'who_caused_auto_accident' and @type = 'text']</value>
      <webElementGuid>8eede5e8-c3c3-43e5-be7c-41162c65fd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='who_caused_auto_accident']</value>
      <webElementGuid>cf32713f-3ce5-4064-94e2-472ee2951684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>5bd09366-7168-4aab-bf24-ab6dae97dabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>ce6ce1dd-358e-42bd-a564-5bbb8e3a5dcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
