<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_IMaskInput-Thu Oct 16 2025 1250_aa0fb6</name>
   <tag></tag>
   <elementGuidId>2c613cbd-6ada-4200-8aa3-11fa6e0d5be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#authorization_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'authorization_phone' and @type = 'text' and @name = 'IMaskInput-Thu Oct 16 2025 12:50:08 GMT+0530 (India Standard Time)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#authorization_phone</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f3c41cf-4a83-401e-9bc0-39e02c0242cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c8fb499a-5a54-4a23-8f22-52b52879a118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>authorization_phone</value>
      <webElementGuid>7fc28002-6920-48be-a132-bdaab2308092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c322cf54-284a-47cf-aa5f-f4a5848a2df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>146d37e4-3118-4cdb-8242-e927bcd56f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IMaskInput-Thu Oct 16 2025 12:50:08 GMT+0530 (India Standard Time)</value>
      <webElementGuid>bcbc2c18-2838-4ec3-be2c-2cb129e9c347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>19ed5a84-830e-47bd-a452-4a813a340816</value>
      <webElementGuid>ca97a323-afbc-4186-874a-23bc608f800b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authorization_phone&quot;)</value>
      <webElementGuid>bd981793-0960-4310-82b1-cb0c3ef4395e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'authorization_phone' and @type = 'text' and @name = 'IMaskInput-Thu Oct 16 2025 12:50:08 GMT+0530 (India Standard Time)']</value>
      <webElementGuid>3bf31fd5-6f26-4eb9-8da9-c3b2df0ff11d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='authorization_phone']</value>
      <webElementGuid>5f3fe160-501d-440c-b812-6834459512c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[4]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>b58962f1-5d02-41c0-85a0-324947e26ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>04f85032-2c92-4c84-86b9-71c4ddab4504</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
