<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_IMaskInput-Thu Oct 16 2025 132737 GMT0530 (India Standard Time)</name>
   <tag></tag>
   <elementGuidId>2fa53b3c-953e-430f-a77f-2335eaf013fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#authorization_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'authorization_phone' and @type = 'text' and @name = 'IMaskInput-Thu Oct 16 2025 13:27:37 GMT+0530 (India Standard Time)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#authorization_phone</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4d42b4f-f382-44bc-913c-10a4f3b34f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7bc978a1-e0ec-4b42-ba5e-9aab5fad30b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>authorization_phone</value>
      <webElementGuid>8ab4bd3a-8fb4-4743-abe6-ef7ce33f09ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>833a83df-a232-4ef5-aa3a-2e62436ac3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>2cffad34-2edb-4170-9c50-f57a8945acb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IMaskInput-Thu Oct 16 2025 13:27:37 GMT+0530 (India Standard Time)</value>
      <webElementGuid>604a6b8a-c095-43b5-ad44-a85202b00e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authorization_phone&quot;)</value>
      <webElementGuid>93fadae8-510f-4677-8956-290ea9a340d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'authorization_phone' and @type = 'text' and @name = 'IMaskInput-Thu Oct 16 2025 13:27:37 GMT+0530 (India Standard Time)']</value>
      <webElementGuid>1a327e5f-e490-47ce-9c79-34335b15abaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='authorization_phone']</value>
      <webElementGuid>d7926690-ffdb-4a36-8c23-e711623bc756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[4]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>58032544-c4ca-441b-b48f-8be75c6972e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>1fb93b41-ffc4-43e0-bd27-f7c68c3705f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
