<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Do you have an attorney involved for _8684dd</name>
   <tag></tag>
   <elementGuidId>96069273-5624-48a0-85da-7233aa944864</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attorney_involved-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id = 'attorney_involved-label' and (text() = 'Do you have an attorney involved for your accident? *' or . = 'Do you have an attorney involved for your accident? *')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Do you have an attorney involved for your accident? *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4d186c7a-1bcc-4fab-b938-cda4ee2a254b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormLabel-root MuiFormLabel-colorPrimary Mui-required css-88235q</value>
      <webElementGuid>6112f0ec-cf81-4948-ae39-70db71bca807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attorney_involved-label</value>
      <webElementGuid>3cde06c6-3977-48ea-8eb0-aa71d7f01b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Do you have an attorney involved for your accident? *</value>
      <webElementGuid>76019b1d-f039-4e42-b6e1-fbbea9c1eca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attorney_involved-label&quot;)</value>
      <webElementGuid>78058c3b-18ca-48ff-9178-0a688999852a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'attorney_involved-label' and (text() = 'Do you have an attorney involved for your accident? *' or . = 'Do you have an attorney involved for your accident? *')]</value>
      <webElementGuid>ca4e5364-c1c0-4450-a993-a04af085392f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='attorney_involved-label']</value>
      <webElementGuid>3ac651d2-374e-458d-94c3-236a51e0aacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[3]/div/div/label</value>
      <webElementGuid>bdf6ae0c-7a91-4bb9-a066-66fd3e0a5bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attorney Information'])[1]/following::label[1]</value>
      <webElementGuid>25afe60a-4917-476c-b7cd-e62a65b244f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Insurance'])[1]/following::label[1]</value>
      <webElementGuid>663bc15b-0388-4b50-9373-794febd32a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::label[1]</value>
      <webElementGuid>a724d0b7-2cce-412c-b391-c6412944b065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::label[2]</value>
      <webElementGuid>9bceb7cd-02b0-4391-a8c2-e29a5a8c75c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Do you have an attorney involved for your accident?']/parent::*</value>
      <webElementGuid>0872ec4c-ccac-4194-b504-d1d9bbfe856e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label</value>
      <webElementGuid>efe44ef0-994e-4e6d-a673-f3ff7a5b813f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
