<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Were you the driver or a passenger</name>
   <tag></tag>
   <elementGuidId>cb80d287-40cd-4dad-89c0-413c9bd66888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#were-you-driver-or-passenger-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id = 'were-you-driver-or-passenger-label' and (text() = 'Were you the driver or a passenger? *' or . = 'Were you the driver or a passenger? *')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Were you the driver or a passenger? *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>59fb7d9f-3757-444c-9939-ceb7cba90a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormLabel-root MuiFormLabel-colorPrimary Mui-required css-88235q</value>
      <webElementGuid>4b4c52c4-a7d0-45a4-8dfd-82229d56be25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>were-you-driver-or-passenger-label</value>
      <webElementGuid>92620308-ae7f-4961-a8d1-dd13ade1cfc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Were you the driver or a passenger? *</value>
      <webElementGuid>90b181d3-134e-49cf-a58e-6f700c5e3f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;were-you-driver-or-passenger-label&quot;)</value>
      <webElementGuid>347785a2-ad09-4604-87cc-7ed770e129d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'were-you-driver-or-passenger-label' and (text() = 'Were you the driver or a passenger? *' or . = 'Were you the driver or a passenger? *')]</value>
      <webElementGuid>17702b72-0b2a-4e77-b6ba-b584a48750ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='were-you-driver-or-passenger-label']</value>
      <webElementGuid>1b0b10bd-9d92-4aeb-956b-494579869a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[2]/div/div/div[3]/div/label</value>
      <webElementGuid>960bd36d-1858-4d77-a191-bba2bea353ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Driver'])[1]/preceding::label[1]</value>
      <webElementGuid>52a80761-62e1-4140-aa0a-ad990794fe46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger'])[1]/preceding::label[2]</value>
      <webElementGuid>5b8b2afc-9476-4f3f-bab9-0863f11486b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Were you the driver or a passenger?']/parent::*</value>
      <webElementGuid>4bd82798-a68c-4bea-9926-a46a3169daaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/label</value>
      <webElementGuid>b4e0b321-e2c6-44d4-a781-3c21f6e14245</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
