<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Do you authorize us to contact you by_d82ab3</name>
   <tag></tag>
   <elementGuidId>c38203cb-79e4-41a3-a96b-529376c81813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#allow-contact-by-email-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id = 'allow-contact-by-email-label' and (text() = 'Do you authorize us to contact you by your email? *' or . = 'Do you authorize us to contact you by your email? *')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Do you authorize us to contact you by your email? *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4056d1f3-2af9-4dae-b104-98ad6070f794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormLabel-root MuiFormLabel-colorPrimary Mui-required css-88235q</value>
      <webElementGuid>f341a279-a765-4638-9323-de6a3da631a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>allow-contact-by-email-label</value>
      <webElementGuid>7d333a0a-4b9e-46b9-9478-5f1a5ea632de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Do you authorize us to contact you by your email? *</value>
      <webElementGuid>b62a1ea5-de02-470b-b2d6-6366806e5d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allow-contact-by-email-label&quot;)</value>
      <webElementGuid>db83f4f0-7eae-44c6-a461-e123aa94da03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'allow-contact-by-email-label' and (text() = 'Do you authorize us to contact you by your email? *' or . = 'Do you authorize us to contact you by your email? *')]</value>
      <webElementGuid>e3b5b5aa-f3a6-441e-bb03-6a0593439aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='allow-contact-by-email-label']</value>
      <webElementGuid>a9d05fb7-9476-4307-a777-866ff859e1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[4]/div/div[3]/div/label</value>
      <webElementGuid>c2fa5105-988c-48f9-808c-eb0831ed2b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/following::label[1]</value>
      <webElementGuid>7654b6f1-b94a-4874-8345-2aae2f27dabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[2]/following::label[2]</value>
      <webElementGuid>d17e194c-ffc4-4c4c-8d16-62f996bdb2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[3]/preceding::label[1]</value>
      <webElementGuid>aa547511-2aa2-4cc8-8af0-59681632af11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[3]/preceding::label[2]</value>
      <webElementGuid>847f1277-b58b-4904-a56e-91c39049ec42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Do you authorize us to contact you by your email?']/parent::*</value>
      <webElementGuid>d193b6d6-8127-4e8e-bf0c-24fcdbc728bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/div/label</value>
      <webElementGuid>de75a937-915d-4475-b9d0-2abce2470c8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
