<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Verify</name>
   <tag></tag>
   <elementGuidId>9681dcea-0b93-40cc-8349-6aa879ce1586</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recaptcha-verify-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id = 'recaptcha-verify-button' and (text() = 'Verify' or . = 'Verify')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Verify&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf62e60f-cb6a-41ed-b094-da78f6beec79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-button-default goog-inline-block</value>
      <webElementGuid>97d3cb00-5154-4435-80f7-64f2a7f90a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recaptcha-verify-button</value>
      <webElementGuid>049a84cc-b29c-4cd6-8913-45c0544685ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9259f2ce-afed-4cda-a207-6002befb321e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>ca990b4f-702b-495c-aa14-96d732672b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-verify-button&quot;)</value>
      <webElementGuid>03d4c8e2-0d5d-4113-a44f-7cbe61f27537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ssn/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-f55v7a9xw24l</value>
      <webElementGuid>994a66e6-a332-4681-b43c-6e4a54cd6a88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'recaptcha-verify-button' and (text() = 'Verify' or . = 'Verify')]</value>
      <webElementGuid>a0245412-c6db-4792-9837-9194eaec49e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='recaptcha-verify-button']</value>
      <webElementGuid>cc9c85b2-03bb-444b-a5fd-3693ec28ba54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect']/div[3]/div[2]/div/div[2]/button</value>
      <webElementGuid>48168e9e-2221-4d93-a2a9-775c7d68c2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='stairs'])[1]/following::button[6]</value>
      <webElementGuid>7fce8841-47ed-48ec-93e1-703307dfd3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verify']/parent::*</value>
      <webElementGuid>e97f0347-999d-4b2a-8a69-490460e8c678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>b4acf9bb-d7c6-422b-b3a8-e4e33e1fa8c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
