<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>katalon-div_id(katalon-rec_elementInfoDiv)</name>
   <tag></tag>
   <elementGuidId>424719af-d15d-4ec1-acc6-d34f518a2e88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#katalon-rec_elementInfoDiv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//katalon-div[@id = 'katalon-rec_elementInfoDiv' and (text() = 'id(&quot;katalon-rec_elementInfoDiv&quot;)' or . = 'id(&quot;katalon-rec_elementInfoDiv&quot;)')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;id(\&quot;katalon-rec_elementInfoDiv\&quot;)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>katalon-div</value>
      <webElementGuid>b04a0370-fec2-401d-bb79-6c50fb3c392c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>katalon-rec_elementInfoDiv</value>
      <webElementGuid>83be2232-f2e3-4bad-bd10-1dbb8cb2d183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
      <webElementGuid>ac392a30-be02-47b2-a2ac-b851dcaa5743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
      <webElementGuid>9730aa98-0cd0-4339-857c-55c86209a143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ssn/Page_MyCareCoverage/iframe_Password_a-f55v7a9xw24l</value>
      <webElementGuid>cf213cfb-ec0d-4df8-acfe-fb18f7ddc363</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//katalon-div[@id = 'katalon-rec_elementInfoDiv' and (text() = 'id(&quot;katalon-rec_elementInfoDiv&quot;)' or . = 'id(&quot;katalon-rec_elementInfoDiv&quot;)')]</value>
      <webElementGuid>2ca532bd-ed60-42ee-864c-e0cc6f46af82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//katalon-div[@id='katalon-rec_elementInfoDiv']</value>
      <webElementGuid>ceab9f4a-6d9c-4a63-9b7e-2b204ea3c49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//katalon-div[@id='katalon']/katalon-div</value>
      <webElementGuid>ba4c2924-06b1-4e52-9130-982d1d288204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms'])[1]/following::katalon-div[2]</value>
      <webElementGuid>6c028688-47e5-4ebe-a77b-3081b0affd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy'])[1]/following::katalon-div[2]</value>
      <webElementGuid>06f2ea10-d6bd-46ab-8b74-54774fe22b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='id(&quot;katalon-rec_elementInfoDiv&quot;)']/parent::*</value>
      <webElementGuid>1d6817d1-a7e6-4230-b08a-1940e75fd7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//katalon-div/katalon-div</value>
      <webElementGuid>969a2dd1-c89f-4daa-b01c-2b5f8ddc5b3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
