<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Your Estimated Income_NumericFormat-Fri Sep 26 2025 104133 GMT0530 (India Standard Time)</name>
   <tag></tag>
   <elementGuidId>cd804012-6ca7-48be-b203-92ce96d13dcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#estimated_income</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='estimated_income']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Enter Your Estimated Income *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2003de75-d206-4bff-bcff-29c703fb5741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df1653c8-2ff9-4a05-8bd9-9b1eac466b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>estimated_income</value>
      <webElementGuid>bc1ba074-0e1a-4521-a323-e6408667d973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>63c58218-8826-4c82-8247-36c16e8a05c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NumericFormat-Fri Sep 26 2025 10:41:33 GMT+0530 (India Standard Time)</value>
      <webElementGuid>a71e8c56-8527-4e73-acf1-a7adda437549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8fb8ae0c-3f68-4676-998f-bb035528bc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>e63180af-9b76-4040-861f-dd80d19463ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;estimated_income&quot;)</value>
      <webElementGuid>eddf0c5a-2ede-41ec-b04a-d0b576fe8614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='estimated_income']</value>
      <webElementGuid>0c8dde0d-826d-44e3-ac02-e61fcbbf7df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div/input</value>
      <webElementGuid>4797eb41-06a6-4652-b665-2d3a1252d087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'estimated_income' and @name = 'NumericFormat-Fri Sep 26 2025 10:41:33 GMT+0530 (India Standard Time)' and @type = 'text']</value>
      <webElementGuid>9c0f0973-8553-4ce6-818a-86bb75c53902</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
