<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_IMaskInput-Thu Sep 25 2025 171737 GMT0530 (India Standard Time)</name>
   <tag></tag>
   <elementGuidId>1d69e759-200b-4e6b-b492-e595c61ca04c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#authorization_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='authorization_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#authorization_phone</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b0ce48e-a793-4e3a-afd1-942e869b5875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb3766ca-b5af-4d52-ab73-1cc25d50cf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>authorization_phone</value>
      <webElementGuid>54f5484c-603b-4f09-8890-c68f0550eddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73629636-3de7-4e29-9ff4-76fde9f727d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>05263859-5089-499c-bab5-b969798d08c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IMaskInput-Thu Sep 25 2025 17:17:37 GMT+0530 (India Standard Time)</value>
      <webElementGuid>03c1ad8f-f70b-47e0-b6bc-fcecdb03f95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;authorization_phone&quot;)</value>
      <webElementGuid>85727f02-b916-462d-bba5-76af55369f07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='authorization_phone']</value>
      <webElementGuid>faebba9f-ebe2-4e83-beb8-0fda00c39a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[3]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>dd1d6677-fe5d-4bfa-b288-244d6786bf0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>8bc4392c-655f-40ca-9788-ffa6d406050f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'authorization_phone' and @type = 'text' and @name = 'IMaskInput-Thu Sep 25 2025 17:17:37 GMT+0530 (India Standard Time)']</value>
      <webElementGuid>2a2921fe-1325-4b39-b8b5-4d5774e8ce1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
