<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_IMaskInput-Thu Sep 25 2025 172412 GMT0530 (India Standard Time)</name>
   <tag></tag>
   <elementGuidId>894a530d-1540-43a9-9f91-801e219794c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employer_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employer_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#employer_phone</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e8912c8-164e-48ba-a823-258ebf3f81c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>180006f1-b9a2-49f7-8bef-d693aeeb919b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employer_phone</value>
      <webElementGuid>c81e2981-9fb9-44ca-8312-f87585a4c828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0880a0b4-b065-47dd-b442-835688cd5328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>6f28b372-05a6-4cfa-8e23-c61d79ac33b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IMaskInput-Thu Sep 25 2025 17:24:12 GMT+0530 (India Standard Time)</value>
      <webElementGuid>8a1e2c24-4035-462a-a7dc-2f60095b26f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employer_phone&quot;)</value>
      <webElementGuid>226c3548-3504-46c8-a061-4ecfd8167b6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employer_phone']</value>
      <webElementGuid>e46c180d-ae32-4691-aaca-fc51fdddaecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[2]/div/div/div[6]/div/div/input</value>
      <webElementGuid>f2b72500-996c-4eab-8aef-9f4157c47df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>23c5d22e-328e-4850-aa8f-582bd5b582d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'employer_phone' and @type = 'text' and @name = 'IMaskInput-Thu Sep 25 2025 17:24:12 GMT+0530 (India Standard Time)']</value>
      <webElementGuid>9da46fe3-5a90-479d-bce4-99282523f9ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
