<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Has the accident been reported to the responsible party</name>
   <tag></tag>
   <elementGuidId>838a2d5e-8ed8-4915-87cb-3e4b49e793f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#was-accident-reported-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id = 'was-accident-reported-label' and (text() = 'Has the accident been reported to the responsible party? *' or . = 'Has the accident been reported to the responsible party? *')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Has the accident been reported to the responsible party? *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>436dd8cd-4c01-41ce-b541-e127313656bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormLabel-root MuiFormLabel-colorPrimary Mui-required css-88235q</value>
      <webElementGuid>b7a9519a-fd28-416f-a742-cde8669f2ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>was-accident-reported-label</value>
      <webElementGuid>e58ff286-7c0b-466d-b992-1c244485c081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Has the accident been reported to the responsible party? *</value>
      <webElementGuid>a9476926-d3e9-4521-bdbd-2e2c039431bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;was-accident-reported-label&quot;)</value>
      <webElementGuid>d8e2636a-5fc2-4a31-9615-c0880b3884bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'was-accident-reported-label' and (text() = 'Has the accident been reported to the responsible party? *' or . = 'Has the accident been reported to the responsible party? *')]</value>
      <webElementGuid>bd2cdc56-6631-482b-b62d-c0d941e1e26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='was-accident-reported-label']</value>
      <webElementGuid>e638c6ec-c079-4a26-aabf-9e1fb51eb71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[2]/div/div/div[5]/div/label</value>
      <webElementGuid>55634736-c95d-4f92-8d80-dd6ee4c296e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::label[1]</value>
      <webElementGuid>a4bae9af-ee95-4242-beb1-92e54419be8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::label[2]</value>
      <webElementGuid>4cc78722-cbf4-40cf-aa52-c0f792fa6c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Has the accident been reported to the responsible party?']/parent::*</value>
      <webElementGuid>bf55dd77-0da4-4bbb-8a2e-a76181f34552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label</value>
      <webElementGuid>0182704a-0375-4f16-b423-cc19c56b394f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
