<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Has a claim been opened with responsible partys insurance</name>
   <tag></tag>
   <elementGuidId>934d1fda-fc5c-4101-ba20-6634fe1e2d4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#was-claim-opened-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id = 'was-claim-opened-label' and (text() = concat(&quot;Has a claim been opened with responsible party&quot; , &quot;'&quot; , &quot;s insurance? *&quot;) or . = concat(&quot;Has a claim been opened with responsible party&quot; , &quot;'&quot; , &quot;s insurance? *&quot;))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Has a claim been opened with responsible party's insurance? *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f161d525-429f-44bb-b733-de0b6d241ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormLabel-root MuiFormLabel-colorPrimary Mui-required css-88235q</value>
      <webElementGuid>7e483798-2b7a-4c08-978e-78f1eb407f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>was-claim-opened-label</value>
      <webElementGuid>26dcdc98-073b-4ed1-af7d-275dfd93b44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Has a claim been opened with responsible party's insurance? *</value>
      <webElementGuid>5d9e5ff4-111f-46ce-afcb-449c3f0d03b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;was-claim-opened-label&quot;)</value>
      <webElementGuid>07d05f68-eb1b-4714-b059-5ac133ee1c62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'was-claim-opened-label' and (text() = concat(&quot;Has a claim been opened with responsible party&quot; , &quot;'&quot; , &quot;s insurance? *&quot;) or . = concat(&quot;Has a claim been opened with responsible party&quot; , &quot;'&quot; , &quot;s insurance? *&quot;))]</value>
      <webElementGuid>b3d807a2-9122-4b16-a38d-22f4c4f48104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='was-claim-opened-label']</value>
      <webElementGuid>a3459545-9279-40c9-bd2f-b2a31cbf0738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[2]/div/div/div[6]/div/label</value>
      <webElementGuid>69c7c65a-35c7-45fa-87de-420830859732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::label[1]</value>
      <webElementGuid>4c7aab82-b6b3-45bf-ad0a-e1ffd4ab5bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::label[2]</value>
      <webElementGuid>67e3cbe0-8fa8-4c56-b79e-9d9846b9a14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[2]/preceding::label[1]</value>
      <webElementGuid>b05f942d-e255-4834-9d4c-e7affbb2d77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::label[2]</value>
      <webElementGuid>5a305c20-8f3d-42cd-8a04-a4df2926466b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/label</value>
      <webElementGuid>a7a0ba2d-38d1-4f62-a181-84b085743cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
