<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Has the accident been reported to the responsible party</name>
   <tag></tag>
   <elementGuidId>838a2d5e-8ed8-4915-87cb-3e4b49e793f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#was-accident-reported-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='was-accident-reported-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Has the accident been reported to the responsible party? *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fdef0ef7-3621-4449-9475-b26dacf41ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormLabel-root MuiFormLabel-colorPrimary Mui-required css-88235q</value>
      <webElementGuid>ff5bf6ce-ffb2-402f-9c08-b7865a80a3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>was-accident-reported-label</value>
      <webElementGuid>984f4559-edc7-4064-90ec-8cba4b60effa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Has the accident been reported to the responsible party? *</value>
      <webElementGuid>9f27a9d0-4b58-428c-bf76-5da58c10080a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;was-accident-reported-label&quot;)</value>
      <webElementGuid>d6f0c1fe-50f3-4736-9d04-ea1e9088f967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='was-accident-reported-label']</value>
      <webElementGuid>5aee8a44-900f-462b-9236-b3d8525385dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[2]/div/div/div[5]/div/label</value>
      <webElementGuid>980adaeb-33e8-4fe1-9cc1-8fcce33b6730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::label[1]</value>
      <webElementGuid>9c03e398-f1d3-4600-a18f-8499b12044d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::label[2]</value>
      <webElementGuid>b5b2f1d2-4f40-4266-ab13-b7d4212be90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Has the accident been reported to the responsible party?']/parent::*</value>
      <webElementGuid>74997835-b2b8-479b-9cac-8a27f2a1ce73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label</value>
      <webElementGuid>c6c4073f-fb7b-4a7d-b4c1-f40dbbfd858a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'was-accident-reported-label' and (text() = 'Has the accident been reported to the responsible party? *' or . = 'Has the accident been reported to the responsible party? *')]</value>
      <webElementGuid>338c1219-794c-49a6-84d6-47f3a2ba3c02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
