<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_zip</name>
   <tag></tag>
   <elementGuidId>1da5800a-47ee-4b63-943d-2eee5ebd1001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'zip' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Zip Code *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e99040e-f049-44f4-9929-54fc770e4eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7825a96b-d73f-454e-ba22-b8dd26b9bfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zip</value>
      <webElementGuid>eef894a5-4399-4a26-a2b4-b40df5bcef25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7348bd5-1c2b-4ebb-8c30-2fb1e7be5f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>464a6ec2-abda-4cff-981f-38d4c97d8b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>c0d651e1-1f31-4863-b77e-843a23bc6dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>1ab19ed2-a426-43e9-bdc6-0219eda1bc72</value>
      <webElementGuid>b0c23e29-b47e-43c9-8ca4-2b3cd4c9353c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zip&quot;)</value>
      <webElementGuid>0770e656-c7c6-4e3d-bdbe-9f3a5ce77dfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'zip' and @type = 'text']</value>
      <webElementGuid>23d06348-2a97-49c2-98f5-d28fab994dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='zip']</value>
      <webElementGuid>1d8d1910-2e0e-4d86-92e3-1829ad951616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[2]/div/div[4]/div[3]/div/div/input</value>
      <webElementGuid>9ad38b29-a7e9-4054-b054-345438bdf810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/input</value>
      <webElementGuid>0c83d3af-fe23-4440-871d-62c78b04475d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
