<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Spouse</name>
   <tag></tag>
   <elementGuidId>a3360bfb-e752-41b0-8520-41a3db925861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#relationship-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'relationship-option-0' and (text() = 'Spouse' or . = 'Spouse')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Spouse&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a6985c4b-14c8-43d6-89e8-a3840bfbfc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>843c2f57-4f5e-4b8e-855c-5cf71f10c737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9c814995-8582-482a-b7c3-f3420c27dcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>relationship-option-0</value>
      <webElementGuid>c6d7cc2b-5253-4498-96c9-c7bc68ddecf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d0ab56b4-3fc8-4012-ac30-9623cca5a407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>82a3d47b-7d12-4b2b-b637-66f4cf668f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68ca99d8-140b-4733-8a43-c1c6a25d4dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>55f58ed4-fe83-4f2f-b721-65c2ef04d016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spouse</value>
      <webElementGuid>7f91bb73-e2cc-46ae-a374-45504bd79c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;relationship-option-0&quot;)</value>
      <webElementGuid>21cba1e6-8760-4ff6-95da-0fba2ada1a5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'relationship-option-0' and (text() = 'Spouse' or . = 'Spouse')]</value>
      <webElementGuid>c873b60e-7834-401b-88a1-011cb3a9f559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='relationship-option-0']</value>
      <webElementGuid>9124fd66-b8a8-45ed-b6a6-b1edeba9d265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='relationship-listbox']/li</value>
      <webElementGuid>331863cd-4c40-4e55-8e83-a391f84befd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Household Member'])[1]/following::li[1]</value>
      <webElementGuid>6dd2b12e-8a83-4de7-941a-b39c79b61736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Child (including adopted child)'])[1]/preceding::li[1]</value>
      <webElementGuid>6091a1ce-9382-4f26-a715-4001a6d0f30d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parent/Step-Parent'])[1]/preceding::li[2]</value>
      <webElementGuid>2d0956d5-2c52-48b8-92fa-349db9d47e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Spouse']/parent::*</value>
      <webElementGuid>77787f27-8b9d-4c81-954d-193eb5b1b538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li</value>
      <webElementGuid>9c2a0ba2-9c49-477d-a028-97263eb07f96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
