<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_html1body1div2div4iframe1_c-x1xggqxapb0t</name>
   <tag></tag>
   <elementGuidId>f7f09e65-6395-484b-86a1-0dccfbe1c05a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-x1xggqxapb0t']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-x1xggqxapb0t&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;c-x1xggqxapb0t&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>919ecc91-96f8-4f37-9e69-5fbae1e28255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>a8983a79-23a4-4051-b958-1902724dbfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-x1xggqxapb0t</value>
      <webElementGuid>2f517110-2d9f-4477-9ab9-2c77c4df3d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2e8895d3-b763-4722-982d-638af6aaec84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>cdc847aa-7b69-4919-b4b2-9a20f017fe58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>af1357b1-f6b6-4d91-9278-5e05b0c1e54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=44LqIOwVrGhp2lJ3fODa493O&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;bft=0dAFcWeA5ttWIIvC7sF3X7jMXM-69pMC6GEgNKDtVkEd4wEpeBCWMCO-yavKmDRvzfsB1S1piFeBP7ty8xJU7_2KjnZn2PEVNghw</value>
      <webElementGuid>726e0e4d-8859-4976-bf99-8f8a8ffc8a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[4]/iframe[1]</value>
      <webElementGuid>5300ac85-d22a-49c9-a00b-bd9e37d45128</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-x1xggqxapb0t']</value>
      <webElementGuid>2c5a366e-468b-4021-a690-3c1735b38c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>ee65a183-3a86-4db9-850d-825583d268fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-x1xggqxapb0t' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=44LqIOwVrGhp2lJ3fODa493O&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;bft=0dAFcWeA5ttWIIvC7sF3X7jMXM-69pMC6GEgNKDtVkEd4wEpeBCWMCO-yavKmDRvzfsB1S1piFeBP7ty8xJU7_2KjnZn2PEVNghw']</value>
      <webElementGuid>7c95862b-e679-4a6c-a2fb-e96a8c5a5ea3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
