<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>17e12e7f-ce23-4e6b-94ec-aa861ed93a84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='6']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6 > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\36 &quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6e237e76-d152-413e-abb3-3ded6fd635f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>ed88f331-c29e-41e5-8b15-518ecebc02ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5BP9aHIQ0Hh140FVpmf2EwZ98pxJBEy3clky3FqygywNSsyI5BsBUZixUb7WzzG1GB4k8Pe2KXt_ney1_zZWar6gdN55THqX46dh6BP3dUpUZOoBLzDe_tW7RYsyhBsmGzycn8VP6d1v6rYo9-saGLOGS_t-qXk5FOKDqW_rOzTUZ4xN_apDGoBSu6CABf9XqYJ2A4rIZwFTr2aa1dqhKbNZm4GIh4d7lqsOR1xGVTmoJi47w&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ</value>
      <webElementGuid>10203640-8b87-47b7-8260-900ae53ea13c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6&quot;)/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>ef4513f7-fad4-4ae3-b90c-04dee248fbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MCC_Portal_2/Import Export/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-x1xggqxapb0t</value>
      <webElementGuid>0b6200b1-c103-4457-b769-ce0980b441cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='6']/div/div/img</value>
      <webElementGuid>01725d3a-8700-4974-8859-1e75ef489773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5BP9aHIQ0Hh140FVpmf2EwZ98pxJBEy3clky3FqygywNSsyI5BsBUZixUb7WzzG1GB4k8Pe2KXt_ney1_zZWar6gdN55THqX46dh6BP3dUpUZOoBLzDe_tW7RYsyhBsmGzycn8VP6d1v6rYo9-saGLOGS_t-qXk5FOKDqW_rOzTUZ4xN_apDGoBSu6CABf9XqYJ2A4rIZwFTr2aa1dqhKbNZm4GIh4d7lqsOR1xGVTmoJi47w&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ')])[7]</value>
      <webElementGuid>5288b9f7-90ea-46b1-82f7-03a2809d14ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>cbb1b5ff-ea9d-4459-8f69-f3a543202997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5BP9aHIQ0Hh140FVpmf2EwZ98pxJBEy3clky3FqygywNSsyI5BsBUZixUb7WzzG1GB4k8Pe2KXt_ney1_zZWar6gdN55THqX46dh6BP3dUpUZOoBLzDe_tW7RYsyhBsmGzycn8VP6d1v6rYo9-saGLOGS_t-qXk5FOKDqW_rOzTUZ4xN_apDGoBSu6CABf9XqYJ2A4rIZwFTr2aa1dqhKbNZm4GIh4d7lqsOR1xGVTmoJi47w&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ']</value>
      <webElementGuid>8d03770e-0fd2-4452-abaa-dcd3ff1b8370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
