<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44_1_2</name>
   <tag></tag>
   <elementGuidId>f21de6f3-98b2-45d3-a698-ed8245456e78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='3']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#3 > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\33 &quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9a22a95a-b263-4b40-8899-ad6f3e9d5082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>7c6c0108-2cbc-4e6c-8b9b-fa611f40dc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5BP9aHIQ0Hh140FVpmf2EwZ98pxJBEy3clky3FqygywNSsyI5BsBUZixUb7WzzG1GB4k8Pe2KXt_ney1_zZWar6gdN55THqX46dh6BP3dUpUZOoBLzDe_tW7RYsyhBsmGzycn8VP6d1v6rYo9-saGLOGS_t-qXk5FOKDqW_rOzTUZ4xN_apDGoBSu6CABf9XqYJ2A4rIZwFTr2aa1dqhKbNZm4GIh4d7lqsOR1xGVTmoJi47w&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ</value>
      <webElementGuid>32214047-dff9-4e6d-adf7-db372dd622ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3&quot;)/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>eaf86eba-34c2-4685-a3cb-76316e744f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MCC_Portal_2/Import Export/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-x1xggqxapb0t</value>
      <webElementGuid>473db536-4407-493d-a9e4-ce4fe01845c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='3']/div/div/img</value>
      <webElementGuid>06349439-0278-4150-87f6-6d68a3a4c363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5BP9aHIQ0Hh140FVpmf2EwZ98pxJBEy3clky3FqygywNSsyI5BsBUZixUb7WzzG1GB4k8Pe2KXt_ney1_zZWar6gdN55THqX46dh6BP3dUpUZOoBLzDe_tW7RYsyhBsmGzycn8VP6d1v6rYo9-saGLOGS_t-qXk5FOKDqW_rOzTUZ4xN_apDGoBSu6CABf9XqYJ2A4rIZwFTr2aa1dqhKbNZm4GIh4d7lqsOR1xGVTmoJi47w&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ')])[4]</value>
      <webElementGuid>9d474bad-e713-4739-bb2b-fefebab10633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div/img</value>
      <webElementGuid>efff43ec-d84f-42d7-8c45-7b23c1e73287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5BP9aHIQ0Hh140FVpmf2EwZ98pxJBEy3clky3FqygywNSsyI5BsBUZixUb7WzzG1GB4k8Pe2KXt_ney1_zZWar6gdN55THqX46dh6BP3dUpUZOoBLzDe_tW7RYsyhBsmGzycn8VP6d1v6rYo9-saGLOGS_t-qXk5FOKDqW_rOzTUZ4xN_apDGoBSu6CABf9XqYJ2A4rIZwFTr2aa1dqhKbNZm4GIh4d7lqsOR1xGVTmoJi47w&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ']</value>
      <webElementGuid>32382c2d-bfec-4fec-b994-9eecf6ccabbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
