<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44_1</name>
   <tag></tag>
   <elementGuidId>fe054ef8-6a7f-4808-b4c0-9e0d5a827f0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='7']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#7 > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\37 &quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>13d5b2b0-a30f-44af-b73b-af8191fbdad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>f91ca53a-526d-4569-a228-d7f33a439efb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5BP9aHIQ0Hh140FVpmf2EwZ98pxJBEy3clky3FqygywNSsyI5BsBUZixUb7WzzG1GB4k8Pe2KXt_ney1_zZWar6gdN55THqX46dh6BP3dUpUZOoBLzDe_tW7RYsyhBsmGzycn8VP6d1v6rYo9-saGLOGS_t-qXk5FOKDqW_rOzTUZ4xN_apDGoBSu6CABf9XqYJ2A4rIZwFTr2aa1dqhKbNZm4GIh4d7lqsOR1xGVTmoJi47w&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ</value>
      <webElementGuid>a0bc1494-869a-476e-b8af-315b6e68d10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7&quot;)/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>1ec96511-f5bd-47c5-b926-4765dc4c57a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/MCC_Portal_2/Import Export/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-x1xggqxapb0t</value>
      <webElementGuid>cbf51b5b-7003-4ff1-8e2f-b3492aa4ee65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='7']/div/div/img</value>
      <webElementGuid>f57d87dd-a0be-46de-91f9-f58d100ed1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5BP9aHIQ0Hh140FVpmf2EwZ98pxJBEy3clky3FqygywNSsyI5BsBUZixUb7WzzG1GB4k8Pe2KXt_ney1_zZWar6gdN55THqX46dh6BP3dUpUZOoBLzDe_tW7RYsyhBsmGzycn8VP6d1v6rYo9-saGLOGS_t-qXk5FOKDqW_rOzTUZ4xN_apDGoBSu6CABf9XqYJ2A4rIZwFTr2aa1dqhKbNZm4GIh4d7lqsOR1xGVTmoJi47w&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ')])[8]</value>
      <webElementGuid>42d27aad-e6fd-405b-b206-059fec9de688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/div/div/img</value>
      <webElementGuid>dfd93c20-c1f3-417b-b6b8-05ade5a7ab98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5BP9aHIQ0Hh140FVpmf2EwZ98pxJBEy3clky3FqygywNSsyI5BsBUZixUb7WzzG1GB4k8Pe2KXt_ney1_zZWar6gdN55THqX46dh6BP3dUpUZOoBLzDe_tW7RYsyhBsmGzycn8VP6d1v6rYo9-saGLOGS_t-qXk5FOKDqW_rOzTUZ4xN_apDGoBSu6CABf9XqYJ2A4rIZwFTr2aa1dqhKbNZm4GIh4d7lqsOR1xGVTmoJi47w&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ']</value>
      <webElementGuid>387308f5-843e-497d-8a9e-233b0ffc5c0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
