<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Did you lose your job in the last 6 months</name>
   <tag></tag>
   <elementGuidId>5519262b-67be-40ce-9dd1-3513775c1fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lost-job-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='lost-job-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Did you lose your job in the last 6 months? *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>354844c5-28f0-4092-a451-cd79e100ecec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormLabel-root MuiFormLabel-colorPrimary Mui-required css-88235q</value>
      <webElementGuid>fe44a1a4-48d2-4958-b81b-8d04135fc689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lost-job-label</value>
      <webElementGuid>8e4514df-7682-4d90-be44-7db5f3e52fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Did you lose your job in the last 6 months? *</value>
      <webElementGuid>f8a5ac14-1534-41c2-8708-0fe6f949f765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lost-job-label&quot;)</value>
      <webElementGuid>42317599-48b1-4a5b-9ffa-a8e9f9e8f72b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='lost-job-label']</value>
      <webElementGuid>f7928460-8943-474b-8a11-4771e55a4d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div[4]/div/div[3]/div/label</value>
      <webElementGuid>9d1a5127-7cce-442d-8389-cabbb7a84899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Income Source'])[1]/following::label[1]</value>
      <webElementGuid>5ccc5a73-dff2-439c-afe9-c8e3c447e7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Income Source'])[1]/following::label[1]</value>
      <webElementGuid>02436686-eccd-40fa-8869-70cd8bbb17fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[6]/preceding::label[1]</value>
      <webElementGuid>395bd48f-3550-485a-a1ef-b14d279b4655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[6]/preceding::label[2]</value>
      <webElementGuid>04e2a3a0-4707-40d6-9ea7-a373aaa5a1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Did you lose your job in the last 6 months?']/parent::*</value>
      <webElementGuid>8bdf8b50-d345-4e94-877b-c8c6d61af80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/div/label</value>
      <webElementGuid>0e9cb8a9-0898-490f-9da1-363cd4f020dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'lost-job-label' and (text() = 'Did you lose your job in the last 6 months? *' or . = 'Did you lose your job in the last 6 months? *')]</value>
      <webElementGuid>71c7dad7-c84a-4375-adf3-d8e863e9db40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
