<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_newtest</name>
   <tag></tag>
   <elementGuidId>38c39509-92c3-46d6-a326-4abb93faffb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;newtest&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4366a3be-967e-4dcd-8ac8-39f779ffc113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiDataGrid-cell MuiDataGrid-cell--textLeft</value>
      <webElementGuid>74f16d18-a9ad-46f5-98e7-b151341afd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>40455120-792c-46b3-a064-36dd9206fd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>campaign_name</value>
      <webElementGuid>13e2a7a3-48c0-4644-8aaa-1fdef6d5eca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-colindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4e08f61c-e645-4ae7-a940-26a8b8f5f495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>aa6c6364-e62d-4a00-9668-817bf43ef923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a220147d-6f9c-4028-89b7-6acec818fbbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7a4875fc-341d-4bc2-b78d-b97666342d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>newtest</value>
      <webElementGuid>f6427da9-0c10-43da-8597-318d2ab180f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>89d278e6-3651-4e4b-b2e4-96c429845870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>newtest</value>
      <webElementGuid>8e04c489-fdbf-4c6f-ac46-b7b0e672bd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root css-101arav&quot;]/div[@class=&quot;MuiStack-root css-1phb13z&quot;]/div[@class=&quot;MuiBox-root css-pjtxm8&quot;]/div[@class=&quot;MuiDataGrid-root MuiDataGrid-root--densityStandard MuiDataGrid-root--noToolbar MuiDataGrid-withBorderColor css-tckwym&quot;]/div[@class=&quot;MuiDataGrid-main css-1f0pawm&quot;]/div[@class=&quot;MuiDataGrid-virtualScroller css-2d5ulg&quot;]/div[@class=&quot;MuiDataGrid-virtualScrollerContent css-1xdhyk6&quot;]/div[@class=&quot;MuiDataGrid-virtualScrollerRenderZone css-1vouojk&quot;]/div[@class=&quot;even MuiDataGrid-row MuiDataGrid-row--firstVisible MuiDataGrid-row--lastVisible&quot;]/div[@class=&quot;MuiDataGrid-cell MuiDataGrid-cell--textLeft&quot;]</value>
      <webElementGuid>81b1f79c-2158-4d31-b336-4d7008609197</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div[3]</value>
      <webElementGuid>7c3a312b-8698-4b2f-a23c-b44a163f6971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='batch12'])[1]/following::div[1]</value>
      <webElementGuid>1c04c6ff-ed48-47d1-ab42-750bbd089ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::div[12]</value>
      <webElementGuid>28c6157e-2a86-4e43-b4ef-c8595f7e8e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='imported_accounts.csv'])[1]/preceding::div[1]</value>
      <webElementGuid>2bd39185-7946-4775-b75f-d392af933bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='processing'])[1]/preceding::div[5]</value>
      <webElementGuid>613d6c0b-2dd6-4a6d-b3d4-567a19d81622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='newtest']/parent::*</value>
      <webElementGuid>92e4a150-454a-46d9-a3bd-5dfd499b5ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[3]</value>
      <webElementGuid>3bae86bc-744c-44ab-ac22-a7bb61cb8d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'newtest' and (text() = 'newtest' or . = 'newtest')]</value>
      <webElementGuid>84c829e7-8449-45ed-a31f-760f451a91c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
