<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_html1body1div2div4iframe1_c-bkkatr76x0b3</name>
   <tag></tag>
   <elementGuidId>c8620438-493f-4ddd-8606-aab3371acba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-bkkatr76x0b3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-bkkatr76x0b3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;c-bkkatr76x0b3&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d3aefa38-0ea4-4ddd-ac8b-ddd6a740e9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>d16af029-f31f-4d3b-95bc-dbb273e32772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-bkkatr76x0b3</value>
      <webElementGuid>1b4f61ac-a028-4231-b96c-aead19c52447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>72097063-a0cb-4fad-b805-34f68a650805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>bf875963-dd6a-4b1c-9cfb-fb4256465582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>51546900-3598-4497-8302-9582df4dd122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=44LqIOwVrGhp2lJ3fODa493O&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;bft=0dAFcWeA4LTShch_UPpldPllxirK0kcJqz9Ftj13ROyrRHyVUfXrq-Z4IddkUDwXRav3IsAExzHt6GnaAMjZZZcBANbJgMX2iKlg</value>
      <webElementGuid>d8662030-0857-4029-9792-e8dc3b5cc9fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[4]/iframe[1]</value>
      <webElementGuid>5ed0b5bb-82ca-49cd-a6b7-6910d5e493ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-bkkatr76x0b3']</value>
      <webElementGuid>7da35313-2371-42ce-872f-2e499c408941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>3c9c6188-95ef-491f-bcae-9d3864edc38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-bkkatr76x0b3' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=44LqIOwVrGhp2lJ3fODa493O&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ&amp;bft=0dAFcWeA4LTShch_UPpldPllxirK0kcJqz9Ftj13ROyrRHyVUfXrq-Z4IddkUDwXRav3IsAExzHt6GnaAMjZZZcBANbJgMX2iKlg']</value>
      <webElementGuid>86464a30-8216-40f9-b3d4-689650f0f94a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
