<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bicycles_rc-image-tile-44_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>108143e8-91e2-450f-b8d8-282001623bf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='8']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8 > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\38 &quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e3243c17-cc9e-4986-ba8a-c9bffdb10bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>96f98e60-db09-48c6-a088-435f1a67177c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ</value>
      <webElementGuid>630c0ba4-72bd-4f6d-b9fa-f82991375a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8&quot;)/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>41eb9250-7397-4767-bddf-d1a427dd94e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/import file/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-bkkatr76x0b3</value>
      <webElementGuid>cd16b4a3-bdbf-4688-8ea7-4d9bff63ac6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='8']/div/div/img</value>
      <webElementGuid>d973a743-8409-484f-892f-c305ed783048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ')])[9]</value>
      <webElementGuid>b5b01758-d522-4ca7-b0c3-683f0d8bac3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
      <webElementGuid>3f99c8c6-31e3-47a4-ba75-53fc3d74e0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ']</value>
      <webElementGuid>4d3662d0-a7a8-4b53-bcc5-43a77ce4346f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
