<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>1163fb69-21c9-4d17-ac99-8ba99da00da2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='10']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#10 > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\31 0&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ef64732f-b0ab-4d9c-9002-0546e8069f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>22ed4eb8-cbaf-43d8-aaf0-29104dac0c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA64Gt3KLRYlhvvjaxt_rdqvzRU0Gb5NNRSXoOZKlkxdBE-RBnYkPecfCz1jv-GJ0wi-lVZBjp1UYnozJJnWYFejxxJpWwO8x4nO5C-YzJItgUU4KpqawLj58oWfeuMrUmwvo_lgyqDdomucUN6J1t7nw-8JFVvJA1cgbI69Eqeuq-vTZGxra9JK7DRnMI3aFpcez_1K38EqLaWZ9gO3FHDbhlxfJeTqmB2Q-k11PDRKOk8uU9o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ</value>
      <webElementGuid>a5a597e3-2745-4b02-ac82-a504c3a2beab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;10&quot;)/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>d2871a8e-f94b-48c2-a173-e37f00b5577b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/import file/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-bkkatr76x0b3</value>
      <webElementGuid>e9b8ac5d-9a4f-4329-9df9-bf5ca97c74fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='10']/div/div/img</value>
      <webElementGuid>e4991dc3-23db-4653-a2b4-900ee5cc337b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA64Gt3KLRYlhvvjaxt_rdqvzRU0Gb5NNRSXoOZKlkxdBE-RBnYkPecfCz1jv-GJ0wi-lVZBjp1UYnozJJnWYFejxxJpWwO8x4nO5C-YzJItgUU4KpqawLj58oWfeuMrUmwvo_lgyqDdomucUN6J1t7nw-8JFVvJA1cgbI69Eqeuq-vTZGxra9JK7DRnMI3aFpcez_1K38EqLaWZ9gO3FHDbhlxfJeTqmB2Q-k11PDRKOk8uU9o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ')])[11]</value>
      <webElementGuid>2b3ea6bf-c495-4a1a-84cd-9181f1cf47d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>d1b4196f-e6f5-4d1e-84da-214b895b685a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA64Gt3KLRYlhvvjaxt_rdqvzRU0Gb5NNRSXoOZKlkxdBE-RBnYkPecfCz1jv-GJ0wi-lVZBjp1UYnozJJnWYFejxxJpWwO8x4nO5C-YzJItgUU4KpqawLj58oWfeuMrUmwvo_lgyqDdomucUN6J1t7nw-8JFVvJA1cgbI69Eqeuq-vTZGxra9JK7DRnMI3aFpcez_1K38EqLaWZ9gO3FHDbhlxfJeTqmB2Q-k11PDRKOk8uU9o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ']</value>
      <webElementGuid>34e77e6f-4b83-4c35-94af-db587932ecb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
