<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44_1_2</name>
   <tag></tag>
   <elementGuidId>45c6f4b3-407e-4dcc-a394-27adb41ec54a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='6']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6 > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\36 &quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3a692236-f07e-4e8b-b099-7b2b5b0a8f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>69215fe8-0cb9-492a-8f11-cef0ab5f3a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA64Gt3KLRYlhvvjaxt_rdqvzRU0Gb5NNRSXoOZKlkxdBE-RBnYkPecfCz1jv-GJ0wi-lVZBjp1UYnozJJnWYFejxxJpWwO8x4nO5C-YzJItgUU4KpqawLj58oWfeuMrUmwvo_lgyqDdomucUN6J1t7nw-8JFVvJA1cgbI69Eqeuq-vTZGxra9JK7DRnMI3aFpcez_1K38EqLaWZ9gO3FHDbhlxfJeTqmB2Q-k11PDRKOk8uU9o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ</value>
      <webElementGuid>d043cba3-6304-4c55-942a-903821cc8211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6&quot;)/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>1769442c-7725-4dcd-be76-f698530f6ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/import file/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-bkkatr76x0b3</value>
      <webElementGuid>ddf75a92-956a-4331-9768-720944147ba1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='6']/div/div/img</value>
      <webElementGuid>79cf853d-1c45-424a-8eaa-1addb81bba79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA64Gt3KLRYlhvvjaxt_rdqvzRU0Gb5NNRSXoOZKlkxdBE-RBnYkPecfCz1jv-GJ0wi-lVZBjp1UYnozJJnWYFejxxJpWwO8x4nO5C-YzJItgUU4KpqawLj58oWfeuMrUmwvo_lgyqDdomucUN6J1t7nw-8JFVvJA1cgbI69Eqeuq-vTZGxra9JK7DRnMI3aFpcez_1K38EqLaWZ9gO3FHDbhlxfJeTqmB2Q-k11PDRKOk8uU9o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ')])[7]</value>
      <webElementGuid>22e1a9df-64e7-4c30-af95-64d33232078c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>bc2d225d-4640-4707-955a-d4ccc4b8dfeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA64Gt3KLRYlhvvjaxt_rdqvzRU0Gb5NNRSXoOZKlkxdBE-RBnYkPecfCz1jv-GJ0wi-lVZBjp1UYnozJJnWYFejxxJpWwO8x4nO5C-YzJItgUU4KpqawLj58oWfeuMrUmwvo_lgyqDdomucUN6J1t7nw-8JFVvJA1cgbI69Eqeuq-vTZGxra9JK7DRnMI3aFpcez_1K38EqLaWZ9gO3FHDbhlxfJeTqmB2Q-k11PDRKOk8uU9o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ']</value>
      <webElementGuid>5737819d-f42c-4d88-8ae6-39dfe2649854</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
