<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>3bde231a-74a6-408a-b0ab-f53bbda13000</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='11']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#11 > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\31 1&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7a0a8a4b-43be-454f-9390-151b2e551619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>a304728d-68a9-43df-8915-d21b4a4d2449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA64Gt3KLRYlhvvjaxt_rdqvzRU0Gb5NNRSXoOZKlkxdBE-RBnYkPecfCz1jv-GJ0wi-lVZBjp1UYnozJJnWYFejxxJpWwO8x4nO5C-YzJItgUU4KpqawLj58oWfeuMrUmwvo_lgyqDdomucUN6J1t7nw-8JFVvJA1cgbI69Eqeuq-vTZGxra9JK7DRnMI3aFpcez_1K38EqLaWZ9gO3FHDbhlxfJeTqmB2Q-k11PDRKOk8uU9o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ</value>
      <webElementGuid>63caa1e2-81d7-4776-8bcf-fdc5d26d95f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;11&quot;)/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>f48a3b8c-8320-4b09-9762-5e9a3ae881d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/import file/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-bkkatr76x0b3</value>
      <webElementGuid>433b6f9c-8c18-4ac8-bf80-cf05467c028a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='11']/div/div/img</value>
      <webElementGuid>6d01eba1-96fe-43a8-a3d6-cc5ff02e0e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA64Gt3KLRYlhvvjaxt_rdqvzRU0Gb5NNRSXoOZKlkxdBE-RBnYkPecfCz1jv-GJ0wi-lVZBjp1UYnozJJnWYFejxxJpWwO8x4nO5C-YzJItgUU4KpqawLj58oWfeuMrUmwvo_lgyqDdomucUN6J1t7nw-8JFVvJA1cgbI69Eqeuq-vTZGxra9JK7DRnMI3aFpcez_1K38EqLaWZ9gO3FHDbhlxfJeTqmB2Q-k11PDRKOk8uU9o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ')])[12]</value>
      <webElementGuid>b145bbbd-10ad-423b-83eb-91eb0d7ad55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/div/div/img</value>
      <webElementGuid>59102914-5c47-4dbb-a140-9e8618e821df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA64Gt3KLRYlhvvjaxt_rdqvzRU0Gb5NNRSXoOZKlkxdBE-RBnYkPecfCz1jv-GJ0wi-lVZBjp1UYnozJJnWYFejxxJpWwO8x4nO5C-YzJItgUU4KpqawLj58oWfeuMrUmwvo_lgyqDdomucUN6J1t7nw-8JFVvJA1cgbI69Eqeuq-vTZGxra9JK7DRnMI3aFpcez_1K38EqLaWZ9gO3FHDbhlxfJeTqmB2Q-k11PDRKOk8uU9o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ']</value>
      <webElementGuid>1a068d1d-5db1-417e-8f95-c6d321fa8b41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
