<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bicycles_rc-image-tile-44_1_2_3</name>
   <tag></tag>
   <elementGuidId>eaec4c8a-2267-4f0b-a3ce-c5e2f75b3684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='10']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#10 > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\31 0&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e7d774cd-8ebb-46fe-9043-ac24f0b40bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>fe6cb125-519b-4ab9-903f-2828ee5be6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ</value>
      <webElementGuid>f25f0efa-9dc3-48b6-972a-c52e792a7fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;10&quot;)/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>69c4ca38-30f9-453a-9f9d-25d885f0a42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/import file/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-bkkatr76x0b3</value>
      <webElementGuid>7f9bc7ea-fb70-4563-9bb4-8843c1dc9b9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='10']/div/div/img</value>
      <webElementGuid>f596ac87-9d1d-4c4a-8e46-2e614507bbc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ')])[11]</value>
      <webElementGuid>27b7e635-c8e3-4cc6-99e3-8edefeb6cfdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>07312cf5-f8bc-4de3-8d57-a117cc38fe0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ']</value>
      <webElementGuid>08c92c39-ec21-4f97-b458-64a7471d7842</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
