<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bicycles_rc-image-tile-44_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>0f9420cd-0949-496b-8bc7-e78fd96ddb9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='1']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1 > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\31 &quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>adaeea4c-279e-490b-a787-6c8746ffdddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>2782eec2-83ae-407e-b1b1-de256eb0dc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ</value>
      <webElementGuid>088610f1-2d4d-443f-bf03-e079891ce31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1&quot;)/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>b4f426c8-8eac-46a7-94a4-328cb2c4bca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/import file/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-bkkatr76x0b3</value>
      <webElementGuid>d6b42b3c-6b0b-48c8-85cb-981aeeaedd26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='1']/div/div/img</value>
      <webElementGuid>59651520-ad61-4b5e-becc-63e307080a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ')])[2]</value>
      <webElementGuid>0528d1b4-d77f-4ff4-bc16-23f7bf2f6c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
      <webElementGuid>abf972dc-656a-4e2b-976d-1430f92289d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ']</value>
      <webElementGuid>eb915856-be98-40a5-ab7b-875cb5a8a2e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
