<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>ad71bd13-e70b-4f00-90c9-2c2f89dfc00f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='3']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#3 > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\33 &quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0ab04427-0991-443a-8a39-157dccc49d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>39193ef5-77da-49eb-b3a3-80b22c99001b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA64Gt3KLRYlhvvjaxt_rdqvzRU0Gb5NNRSXoOZKlkxdBE-RBnYkPecfCz1jv-GJ0wi-lVZBjp1UYnozJJnWYFejxxJpWwO8x4nO5C-YzJItgUU4KpqawLj58oWfeuMrUmwvo_lgyqDdomucUN6J1t7nw-8JFVvJA1cgbI69Eqeuq-vTZGxra9JK7DRnMI3aFpcez_1K38EqLaWZ9gO3FHDbhlxfJeTqmB2Q-k11PDRKOk8uU9o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ</value>
      <webElementGuid>8977f53f-0267-46dc-82c7-898f30cb4d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3&quot;)/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>73ac7d64-7999-4d08-8f04-60d0f2e5f4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/import file/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-bkkatr76x0b3</value>
      <webElementGuid>6443ba6b-028e-4d45-a301-6211bad89fe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='3']/div/div/img</value>
      <webElementGuid>a3b29277-4ac6-4b75-a4be-b1d94ec07f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA64Gt3KLRYlhvvjaxt_rdqvzRU0Gb5NNRSXoOZKlkxdBE-RBnYkPecfCz1jv-GJ0wi-lVZBjp1UYnozJJnWYFejxxJpWwO8x4nO5C-YzJItgUU4KpqawLj58oWfeuMrUmwvo_lgyqDdomucUN6J1t7nw-8JFVvJA1cgbI69Eqeuq-vTZGxra9JK7DRnMI3aFpcez_1K38EqLaWZ9gO3FHDbhlxfJeTqmB2Q-k11PDRKOk8uU9o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ')])[4]</value>
      <webElementGuid>6678f8b5-30ff-4cc1-84a0-0804473d597f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div/img</value>
      <webElementGuid>dfaece81-e275-4fc3-89f3-99d4e5d1dc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA64Gt3KLRYlhvvjaxt_rdqvzRU0Gb5NNRSXoOZKlkxdBE-RBnYkPecfCz1jv-GJ0wi-lVZBjp1UYnozJJnWYFejxxJpWwO8x4nO5C-YzJItgUU4KpqawLj58oWfeuMrUmwvo_lgyqDdomucUN6J1t7nw-8JFVvJA1cgbI69Eqeuq-vTZGxra9JK7DRnMI3aFpcez_1K38EqLaWZ9gO3FHDbhlxfJeTqmB2Q-k11PDRKOk8uU9o&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ']</value>
      <webElementGuid>a169a3ca-98f0-45c6-a9c0-1ffdb69ea32f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
