<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bicycles_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>b3313375-badd-4d57-9299-d7828901496e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='4']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4 > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\34 &quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>678cd5c0-e8e8-41d8-9c96-8bda90304533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>83f3235e-a3ef-4f10-8da0-ef3cf1562e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ</value>
      <webElementGuid>05ec47f7-f05e-48e4-a9cc-3665bff29015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4&quot;)/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>6d7f25a9-55a2-4de9-b4a7-cd30e6a72af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/import file/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-bkkatr76x0b3</value>
      <webElementGuid>078fdd85-4525-46a8-a69c-8cef8575e58c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='4']/div/div/img</value>
      <webElementGuid>89e5bb5b-a73a-4c74-a327-7889e17d6c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ')])[5]</value>
      <webElementGuid>f08d9754-54ea-45a2-922d-2ac4770b15d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/img</value>
      <webElementGuid>8cb8a7a1-96e2-45a8-aa75-ab0c31a08f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ']</value>
      <webElementGuid>4c5b7b21-a67f-4d66-8e0f-16a6b81a5ae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
