<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bicycles_rc-image-tile-44_1_2</name>
   <tag></tag>
   <elementGuidId>a0bbc1f1-59a6-4930-b9e7-7d5a0c1c972f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='6']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#6 > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\36 &quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d14b080b-d9e5-41d5-bfd0-054733172160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>4219ecfc-b06a-4c12-8cf0-2e025c133f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ</value>
      <webElementGuid>cb989f04-ebf6-4b67-99d1-25e045985c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;6&quot;)/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>51870064-8c8e-404f-a2a2-f655a900bd04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/import file/Page_MyCareCoverage/iframe_html1body1div2div4iframe1_c-bkkatr76x0b3</value>
      <webElementGuid>6e6015a2-0801-4ce8-a461-30552e59fee5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='6']/div/div/img</value>
      <webElementGuid>f0c03c11-d7bc-47dd-8b65-21a50550c063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ')])[7]</value>
      <webElementGuid>3559cbc0-92d9-4c82-a9d3-a9aba1c1ad78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>4a0ff527-c49d-4ead-b4c5-b8f0fb0dba76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA5Tg0A06fH9XIb6sz0ZWr-ObmLLSichBQwVBt-eCjp1pd6gXP7cIBDOdbOtEZ76yLsakrfmC6qI905b245eFgP2fOtnS6CEcumBYnc1pWFtUgWbGhE_JZ7Rg4EHWQWOIWt0g5N3c5bDBgpR-ISZ5m-Z8yBPKitKovxp0-wXF1dZkVlaGXqmpckf4EcCWULx3_rxWxfWf0nVXg-TcA-dnofv3HyA6Y7h3ywpph7wW6Bf-vfDM0c&amp;k=6LdPjuMpAAAAAK_PEU9NVRPuSvnIA61u7ruNLurJ']</value>
      <webElementGuid>f22219b3-6e46-447f-86c6-77fc3402781a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
