<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Your Estimated Income_NumericFormat-Thu Oct 23 2025 013152 GMT0530 (India Standard Time)</name>
   <tag></tag>
   <elementGuidId>c99273ff-40a1-45e7-8134-08769899d31d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#estimated_income</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'estimated_income' and @name = 'NumericFormat-Thu Oct 23 2025 01:31:52 GMT+0530 (India Standard Time)' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Enter Your Estimated Income *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>495226f8-09ba-4eda-9911-faa90c603579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7cc70d0d-3f37-4437-b263-2571178ff56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>estimated_income</value>
      <webElementGuid>067d6e9f-79ce-481f-b346-a41d47f7667a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1o6z5ng</value>
      <webElementGuid>8c19ae0f-b3fc-4355-b1c2-2c1133a6eb25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NumericFormat-Thu Oct 23 2025 01:31:52 GMT+0530 (India Standard Time)</value>
      <webElementGuid>e4f8afbb-4a34-49b4-b136-c3082bc71799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6cd8116f-cead-420c-8412-97e7a40a8e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>2061634c-05f4-4d70-81f4-306e14cf28ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;estimated_income&quot;)</value>
      <webElementGuid>cc23a3f8-2886-4aef-b595-41d9ff7a7200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'estimated_income' and @name = 'NumericFormat-Thu Oct 23 2025 01:31:52 GMT+0530 (India Standard Time)' and @type = 'text']</value>
      <webElementGuid>16eba8e0-cc0f-4ac0-b990-73410c245334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='estimated_income']</value>
      <webElementGuid>6ee3408a-b29a-4a18-95eb-81f613c853b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div/input</value>
      <webElementGuid>f2e2b22a-5d92-40a7-b9d2-1df512912cde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
