<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Social Security Number_ssn-Wed Sep 24_1df0b7</name>
   <tag></tag>
   <elementGuidId>f0995779-4f05-4eaf-9e07-183704cac065</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=':rt:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Social Security Number *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16e51a97-df1b-47a5-81a8-80a2b366ac70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4544ad03-9316-4e70-ba0a-7720a438aadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:rt:-helper-text</value>
      <webElementGuid>17d49fbd-1074-4898-bb2c-33bdb7ca2fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>e3b1074e-1809-4ac1-9087-ccd92671070e</value>
      <webElementGuid>0a04f58d-02f9-4f3b-b79b-f1b6b12d5b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:rt:</value>
      <webElementGuid>242c2bc6-33c0-4838-99f6-1e754fd2a813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ssn-Wed Sep 24 2025 20:20:08 GMT+0530 (India Standard Time)</value>
      <webElementGuid>0d9a9a19-ad8e-4901-85d0-f24f544a8476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fdfed749-1221-43bf-b546-f7bce88d15d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall MuiInputBase-inputAdornedEnd css-b52kj1</value>
      <webElementGuid>bb5481b0-8bfb-48f9-95a0-cdb54afd940d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>*</value>
      <webElementGuid>0abfab74-a899-42b9-a707-f71d1fc790ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rt:&quot;)</value>
      <webElementGuid>4cce6c6f-967d-4f51-aabf-10f820518147</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id=':rt:']</value>
      <webElementGuid>a1db2dc3-c991-4754-a49f-e95e8298a7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div/div/div/div[10]/div/div/input</value>
      <webElementGuid>042eb4b0-5c26-4131-9bb8-aa8f4b07113a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/input</value>
      <webElementGuid>932aa779-9d5c-403b-a9b3-9550f2a3c4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = ':rt:' and @name = 'ssn-Wed Sep 24 2025 20:20:08 GMT+0530 (India Standard Time)' and @type = 'text']</value>
      <webElementGuid>f7400c36-deb1-46a5-a26c-972b8ad8f29f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
