<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Social Security Number_ssn-Wed Sep 24_1df0b7</name>
   <tag></tag>
   <elementGuidId>f0995779-4f05-4eaf-9e07-183704cac065</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(., 'SSN') or contains(., 'Social Security')]/following::input[@type='text'][1]&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Social Security Number *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4b673cf-7ee9-46e2-8ce0-aa7826a1584f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6bc6b68e-9509-4be5-b037-5d0a26d7013d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:rt:-helper-text</value>
      <webElementGuid>b9ea92c1-e598-4588-89f6-14422e9a2dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>e3b1074e-1809-4ac1-9087-ccd92671070e</value>
      <webElementGuid>778cccbf-7b9f-4194-93a3-25b47a85220f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:rt:</value>
      <webElementGuid>0e88fd7b-ecb1-462e-bee3-083022033806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ssn-Wed Sep 24 2025 20:20:08 GMT+0530 (India Standard Time)</value>
      <webElementGuid>a1624efe-7bf3-4175-916d-de7f56bf18f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bfc72095-417c-4155-ab0f-26c023661ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall MuiInputBase-inputAdornedEnd css-b52kj1</value>
      <webElementGuid>d39b860a-0ee4-485e-b6b0-61fed794a937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>*</value>
      <webElementGuid>94c99fdf-d8ae-4c6c-ad1e-0955bf8f8272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rt:&quot;)</value>
      <webElementGuid>e04899f5-372e-4256-946a-50fb22072e25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id=':rt:']</value>
      <webElementGuid>d24ea41d-a3a9-4798-9b7d-5465e5ae1517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/form/div/div/div/div/div[10]/div/div/input</value>
      <webElementGuid>bf5a3f25-c217-477f-9c22-237907659e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/input</value>
      <webElementGuid>2e2f1567-1aa6-4472-a140-81cbc9edef7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = ':rt:' and @name = 'ssn-Wed Sep 24 2025 20:20:08 GMT+0530 (India Standard Time)' and @type = 'text']</value>
      <webElementGuid>fd9c0465-858a-46a5-af13-274ed65c9fa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
